[package]
name = "ferritex"
version = "0.1.0"
edition = "2024"
description = "Native Rust CLI to convert LaTeX to DOCX"
license = "MIT"
authors = ["Vladislav Kuzmin <https://github.com/principalwater>"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
docx-rs = "0.4.19"
env_logger = "0.11.9"
log = "0.4.29"
quick-xml = "0.39.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
walkdir = "2.5.0"
zip = "8.1.0"
