[package]
name = "ferritex-renderer-pdf"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
description = "PDF renderer backend for ferritex"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
ferritex-core = { path = "../ferritex-core" }
log = { workspace = true }
tectonic = { version = "0.15.0", features = ["external-harfbuzz"] }
